[global.config]
    as = 65535
    router-id = "127.0.0.1"
    port = 179
    local-address-list = ["0.0.0.0"]

[[peer-groups]]
    [peer-groups.config]
        peer-group-name = "dynamic"
        peer-as = 0
    [peer-groups.transport.config]
        passive-mode = true
    [[peer-groups.afi-safis]]
        [peer-groups.afi-safis.config]
            afi-safi-name = "ipv4-unicast"

[[dynamic-neighbors]]
    [dynamic-neighbors.config]
        prefix = "0.0.0.0/0"
        peer-group = "dynamic"
